---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z30n7bib7md1/public_html/
    - /bin/rsync -av index.html $DEPLOYPATH 
    - /bin/rsync -av assets/ $DEPLOYPATH 
    - /bin/rsync -av img/ $DEPLOYPATH 